##Import the Libraries


In [1]:
import numpy as np
 

##GLobal variables

In [2]:
hidden_nodes = 2
epoch = 1
lr = 0.003

## Genarate Random Value

In [3]:
Input_data = np.random.randint(100,size=(1000,3))
Output_data =np.random.randint(2, size =(1000,1))

print(f"The dim of the input : {Input_data.shape}")
print(f"the data input : {Input_data[:10]} ")

print("-----------------------------------------------------------------------------")

print(f"The dim of the output : {Output_data.shape}")
print(f"the data output : {Output_data[:10]} ")

The dim of the input : (1000, 3)
the data input : [[46 42 34]
 [70 51 53]
 [93 98 46]
 [64 50 53]
 [67 24  0]
 [ 4 55 31]
 [87 56 63]
 [84  2 68]
 [69 66 68]
 [83 60 16]] 
-----------------------------------------------------------------------------
The dim of the output : (1000, 1)
the data output : [[1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]] 


## Create Neural Network



In [13]:
# function to create a NN
def NeuralNetwork( input_nodes, hidden_nodes, output_nodes):
  #create the weights matrix input-hidden
  weights_ih = np.round(np.random.uniform(-1,1, size =(hidden_nodes,input_nodes)),2)
  #Create the weights matrix hidden-output
  weights_ho = np.round(np.random.uniform(-1,1, size=(output_nodes, hidden_nodes)),2)
  #Create the bias hidden_nodes
  bias_h= np.random.randint(2,size=(hidden_nodes,1))
  #Create the bias output_nodes
  bias_o = np.random.randint(2,size=(hidden_nodes,1))

  return weights_ih,weights_ho,bias_h,bias_o

  

In [15]:
#Create the network
input_nodes = Input_data.shape[1] # number of features in the dataset
output_nodes = Output_data.shape[1] #number of output in the dataset
weights_ih,weights_ho,bias_h,bias_o = NeuralNetwork(input_nodes,hidden_nodes,output_nodes)

print(bias_o)

[[1]
 [1]]


## Split the Data

In [6]:
# we gonna use 60% of the dataset for training and 40% others for test 

#first we should shuffle the data
print(f"before shuffle {Input_data[:5]}")
np.random.shuffle(Input_data)
print(f"after shuffling  : {Input_data[:5]}")

before shuffle [[46 42 34]
 [70 51 53]
 [93 98 46]
 [64 50 53]
 [67 24  0]]
after shuffling  : [[32 82 60]
 [14 57 42]
 [24 83  9]
 [ 6 43 65]
 [30 64 74]]


In [7]:
def split_data(data,size ):

  index = int(data.shape[0] * size)

  train_data = data[:index]
  test_data = data[index:]

  return train_data, test_data

#split the train dataset 
X_train, X_test = split_data(Input_data,0.6)

#split the test dataset
y_train, y_test = split_data(Output_data,0.6)

print(f"the dim of the Train input: {X_train.shape}")
print(f"the dim of the Train output: {X_test.shape}")

print(f"the dim of the test input : {y_train.shape}")
print(f"the dim of the test output: {y_test.shape}")

the dim of the Train input: (600, 3)
the dim of the Train output: (400, 3)
the dim of the test input : (600, 1)
the dim of the test output: (400, 1)


## Standarization

In [8]:
from sklearn import preprocessing

scaler = preprocessing.StandardScaler().fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

print(f"scaled train input dim:{X_train.shape}")
print(f"scaled test input dim:{X_test.shape}")




#without built-in function
#input_data = (X_train - np.mean(X_train))/np.std(X_train)

scaled train input dim:(600, 3)
scaled test input dim:(400, 3)


##FeedForward Function


In [9]:
def sigmoid(value):
  return 1 / 1 + np.exp(-value)

def Matrix_operation(input):
  sum = 0
  output =np.zeros(weights_ih.shape[0],dtype=float)
  for i in range(len(weights_ih)):
      sum = np.sum(np.multiply(input , weights_ih[i]))
  output[i] =sigmoid(sum + bias_h[i])
  
  return output


def feedforward(input,weights_ih,bias_h):
  g = Matrix_operation(input)

  return g[0]


  

  

  
  
  
  


for i in range(epoch):
  for j in range(len(X_train)):
    print(feedforward(X_train[j],weights_ih,bias_h))



  

0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
